CREATE OR REPLACE DATABASE HOSPITAL_ANALYTICS;

CREATE OR REPLACE SCHEMA HOSPITAL_ANALYTICS.PUBLIC;

USE DATABASE HOSPITAL_ANALYTICS;

USE SCHEMA PUBLIC;

CREATE WAREHOUSE IF NOT EXISTS HOSPITAL_WH
WAREHOUSE_SIZE = 'X-SMALL'
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

USE WAREHOUSE HOSPITAL_WH;

CREATE OR REPLACE STAGE HOSPITAL_STAGE;

CREATE OR REPLACE TABLE HOSPITAL_PATIENTS_RAW (
    Patient_ID VARCHAR,
    Age NUMBER,
    Gender VARCHAR,
    Condition VARCHAR,
    Medication VARCHAR,
    Admission_Date DATE,
    Discharge_Date DATE,
    Patient_State VARCHAR,
    Year_of_Admission NUMBER,
    Length_of_Stay NUMBER,
    Readmission VARCHAR,
    Outcome VARCHAR,
    Satisfaction NUMBER,
    Insurance_Claimed VARCHAR,
    Total_Cost NUMBER
);
CREATE OR REPLACE FILE FORMAT HOSPITAL_CSV_FORMAT
TYPE = CSV
FIELD_DELIMITER = ','
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '')
DATE_FORMAT = 'DD-MM-YYYY';


COPY INTO HOSPITAL_PATIENTS_RAW
FROM '@HOSPITAL_STAGE/Hospital Patient .csv'
FILE_FORMAT = HOSPITAL_CSV_FORMAT
ON_ERROR = 'CONTINUE';

SELECT *
FROM HOSPITAL_PATIENTS_RAW
LIMIT 10;


SELECT COUNT(*) AS TOTAL_ROWS
FROM HOSPITAL_PATIENTS_RAW;

DESC TABLE HOSPITAL_PATIENTS_RAW;

SELECT
    COUNT(*) AS TOTAL_ROWS,
    COUNT_IF(PATIENT_ID IS NULL) AS MISSING_PATIENT_ID,
    COUNT_IF(AGE IS NULL) AS MISSING_AGE,
    COUNT_IF(GENDER IS NULL) AS MISSING_GENDER,
    COUNT_IF(CONDITION IS NULL) AS MISSING_CONDITION,
    COUNT_IF(ADMISSION_DATE IS NULL) AS MISSING_ADMISSION_DATE,
    COUNT_IF(DISCHARGE_DATE IS NULL) AS MISSING_DISCHARGE_DATE,
    COUNT_IF(TOTAL_COST IS NULL) AS MISSING_TOTAL_COST
FROM HOSPITAL_PATIENTS_RAW;

SELECT
    CONDITION,
    COUNT(*) AS PATIENT_COUNT
FROM HOSPITAL_PATIENTS_RAW
GROUP BY CONDITION
ORDER BY PATIENT_COUNT DESC;